config/routes.rb
Ranprince::Application.routes.draw do

  resources :apps do
    resources :ranking, :controller => :score_reports, :only => [:index]  
  end

  namespace :api do
    resources :ranking, :only => [:index]
    resources :player, :only => [:create]
    resources :score_reports, :only => [:create]
  end

  resources :devices

  root :to => 'apps#index'

end

app/models/app.rb
# -*- coding: utf-8 -*-
class App < ActiveRecord::Base
  attr_accessible :icon, :name, :store_url

  has_many :score_reports
  has_attached_file :icon,
    :path => ":rails_root/public/images/:class/:attachment/:id/:style.:extension",
    :url => "/images/:class/:attachment/:id/:style.:extension"
    
  # Validation
  validates :name, :presence => true, :length => { :maximum => 100 }
  validates :store_url, :format => { :with => /^https?:\/\/.*/i, :allow_blank => true }, :length => { :maximum => 255 }

  before_create do |app|
    milliseconds = Time.now.instance_eval { '%s.%03d' % [strftime('%Y%m%d%H%M%S'), (usec / 1000.0).round] }
    write_attribute(:app_key, Digest::SHA2.hexdigest("#{app.name}#{milliseconds}"))
  end

  def app_key=(value)
    p 'This attribute is read only.'
  end
end

app/models/device.rb
class Device < ActiveRecord::Base
  attr_accessible :name, :key
  
  has_many :score_reports

  # Validation
  validates :name, :presence => true, :length => { :maximum => 100 }
  validates :key, :presence => true, :uniqueness => true, :length => { :maximum => 100 }

  OTHER_DEVICE_ID = 1
end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :email, :uid

  has_many :players

  # Validation
  validates :name, :presence => true, :uniqueness => true, :length => { :maximum => 100 }
  validates :uid, :presence => true, :uniqueness => true, :length => { :maximum => 255 }
end

app/models/score_report.rb
class ScoreReport < ActiveRecord::Base
  attr_accessible :score

  belongs_to :app
  belongs_to :device
  belongs_to :player

  # Validation
  validates :app_id, :presence => true
  validates :player_id, :presence => true
  validates :score, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 9999999999999 }

  # Scope
  scope :score_asc, order(:score, :created_at)
  scope :score_desc, order('score desc', :created_at)
  scope :score_order, lambda { |t| t == 'asc' ? self.score_asc : self.score_desc }
  scope :daily, where(:created_at => Time.now.beginning_of_day..Time.now.end_of_day)
  scope :weekly, where(:created_at => (Time.now - 7.day).beginning_of_day..Time.now.end_of_day)
  scope :monthly, where(:created_at => (Time.now - 1.month).beginning_of_day..Time.now.end_of_day)

  def self.ranking_search(params)
    app = params[:app_id].present? ? App.find_by_id(params[:app_id]) : App.find_by_app_key(params[:app_key])
    score_reports = ScoreReport.where(:app_id => app.id)
    order_param = params[:order].present? ? params[:order].downcase : nil
    score_reports = score_reports.score_order(order_param)
    if params[:device].present?
      device = Device.where(:key => params[:device].downcase).first
      score_reports = score_reports.where(:device_id => device.id) if device.present?
    end
    if params[:time_type].present?
      case params[:time_type].downcase
        when TimeType::DAILY
          score_reports = score_reports.daily
        when TimeType::WEEKLY
          score_reports = score_reports.weekly
        when TimeType::MONTHLY
          score_reports = score_reports.monthly
      end
    end
    score_reports
  end
end

app/models/time_type.rb
class TimeType
  ALL = 'all'
  DAILY = 'daily'
  WEEKLY = 'weekly'
  MONTHLY = 'monthly'

  def self.names
    [self::ALL, self::DAILY, self::WEEKLY, self::MONTHLY]
  end
end

app/controllers/api/base_controller.rb
# -*- coding: utf-8 -*-
class Api::BaseController < ApplicationController
  private
  def authenticate
    @app = App.find_by_app_key(params[:app_key])
    return render :json => 'error', :status => :bad_request unless @app.present?
  end
end

app/controllers/api/player_controller.rb
# -*- coding: utf-8 -*-
class Api::PlayerController < Api::BaseController
  def create
    player = Player.new
    player.name = params[:name]
    player.uid = params[:uid]
    return render :json => 'error', :status => :bad_request unless player.save
    render :json => player
  end
end

app/controllers/api/ranking_controller.rb
# -*- coding: utf-8 -*-
class Api::RankingController < Api::BaseController
  before_filter :authenticate
  
  def index
    render :json => ScoreReport.ranking_search(params)
  end
end

app/controllers/api/score_reports_controller.rb
# -*- coding: utf-8 -*-
class Api::ScoreReportsController < Api::BaseController
  before_filter :authenticate

  def create
    device = Device.find_by_key(params[:device])
    if device.blank? && params[:device].present?
      device = Device.new
      device.name = params[:device]
      device.key = params[:device]
      device.save
    end
    player = Player.find_by_uid(params[:uid])

    score_report = ScoreReport.new
    score_report.score = params[:score].to_f
    score_report.app_id = @app.id
    score_report.device_id = device.id if device.present?
    score_report.player_id = player.id if player.present?
    return render :json => 'error', :status => :bad_request unless score_report.save
    render :json => score_report
  end
end

app/controllers/application_controller.rb
# -*- coding: utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/apps_controller.rb
# -*- coding: utf-8 -*-
class AppsController < ApplicationController
  def index
    @apps = App.all
  end

  def show
    @app = App.find(params[:id])
  end

  def new
    @app = App.new
  end

  def edit
    @app = App.find(params[:id])
  end

  def create
    @app = App.new(params[:app])
    if @app.save
      redirect_to @app, notice: 'App was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @app = App.find(params[:id])
    if @app.update_attributes(params[:app])
      redirect_to @app, notice: 'App was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @app = App.find(params[:id])
    @app.destroy
    redirect_to apps_url
  end
end

app/controllers/devices_controller.rb
# -*- coding: utf-8 -*-
class DevicesController < ApplicationController
  def index
    @devices = Device.all
  end

  def show
    @device = Device.find(params[:id])
  end

  def new
    @device = Device.new
  end

  def edit
    @device = Device.find(params[:id])
  end

  def create
    @device = Device.new(params[:device])
    if @device.save
      redirect_to @device, notice: 'Device was successfully created.'
    else
      render action: "new"
    end
  end
  def update
    @device = Device.find(params[:id])
    if @device.update_attributes(params[:device])
      redirect_to @device, notice: 'Device was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @device = Device.find(params[:id])
    @device.destroy
    redirect_to devices_url
  end
end

app/controllers/score_reports_controller.rb
class ScoreReportsController < ApplicationController
  def index
    @app = App.find(params[:app_id])
    @score_reports = ScoreReport.ranking_search(params)
    @order_param = ['asc', 'desc'].find{ |v| v != params[:order] }
    @device_key = nil
    if params[:device].present?
      device = Device.where(:key => params[:device]).first
      @device_key = device.key if device.present?
    end
    @time_type_name = params[:time_type].present? ? params[:time_type] : nil
  end
end

app/helpers/api/player_helper.rb
module Api::PlayerHelper
end

app/helpers/api/ranking_helper.rb
module Api::RankingHelper
end

app/helpers/api/score_reports_helper.rb
module Api::ScoreReportsHelper
end

app/helpers/application_helper.rb
# -*- coding: utf-8 -*-
module ApplicationHelper
end

app/helpers/apps_helper.rb
# -*- coding: utf-8 -*-
module AppsHelper
end

app/helpers/score_reports_helper.rb
module ScoreReportsHelper
end

app/views/apps/_form.html.erb
<%= form_for @app, :html => { :multipart => true, :class => 'form-horizontal' } do |f| %>
  <% if @app.errors.any? %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h4><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h4>
      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'input-xlarge' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :store_url, :class => 'control-label' %>
    <div class="controls">
    <%= f.text_field :store_url, :class => 'input-xlarge' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :icon, :class => 'control-label' %>
    <div class="controls">
      <%= image_tag @app.icon.url if @app.icon.present? %><br />
      <%= f.file_field :icon %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.button raw('<i class="icon-ok icon-white"></i> Save'), :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<ul class="breadcrumb step-nav">
  <li><%= link_to 'Application List', apps_path %> <span class="divider">/</span>
  <li><%= link_to @app.name, @app %> <span class="divider">/</span>
  <li>Editing
</ul>
<div class="row page-title-container">
  <div class="span6">
    <h2>Editing Application</h2>
  </div>
  <div class="span6">
  </div>
</div>
<%= render 'form' %>

app/views/apps/index.html.erb
<div class="row page-title-container">
  <div class="span6">
    <h2>Application List</h2>
  </div>
  <div class="span6">
    <%= link_to raw('<i class="icon-plus icon-white"></i> New App'), new_app_path, :class => 'btn btn-success pull-right' %>
  </div>
</div>
<table class="table table-bordered table-striped">
  <tr>
    <th>Icon</th>
    <th>Name</th>
    <th>Store url</th>
    <th>Application Key</th>
    <th>Ranking</th>
  </tr>
<% @apps.each do |app| %>
  <tr>
    <td><%= image_tag app.icon.url if app.icon.present? %></td>
    <td><%= link_to app.name, app %></td>
    <td><%= link_to app.store_url, app.store_url, :target => '_blank' %></td>
    <td><%= app.app_key %></td>
    <td><%= link_to raw('<i class="icon-signal icon-white"></i> Ranking'), app_ranking_index_path(app), :class => 'btn btn-info' %></td>
  </tr>
<% end %>
</table>

app/views/apps/new.html.erb
<ul class="breadcrumb step-nav">
  <li><%= link_to 'Application List', apps_path %> <span class="divider">/</span>
  <li>New
</ul>
<div class="row page-title-container">
  <div class="span6">
    <h2>New Application</h2>
  </div>
  <div class="span6">
  </div>
</div>
<%= render 'form' %>

app/views/apps/show.html.erb
<ul class="breadcrumb step-nav">
  <li><%= link_to 'Application List', apps_path %> <span class="divider">/</span>
  <li><%= @app.name %>
</ul>
<div class="row page-title-container">
  <div class="span6">
    <h2>Application Details</h2>
  </div>
  <div class="span6">
  </div>
</div>
<% if notice.present? %>
<div class="alert alert-info">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <%= notice %>
</div>
<% end %>
<dl class="dl-horizontal detail-container">
  <% if @app.icon.present? %>
  <dt>Icon:
  <dd><%= image_tag @app.icon.url %>
  <% end %>
  <dt>Name:
  <dd><%= @app.name %>
  <dt>Application Key:
  <dd><%= @app.app_key %>
  <dt>Store url:
  <dd><%= @app.store_url %>
</dl>
<div class="form-actions">
  <%= link_to raw('<i class="icon-edit icon-white"></i> Edit'), edit_app_path(@app), :class => 'btn btn-info' %>
  <%= link_to raw('<i class="icon-trash icon-white"></i> Destroy'), '#destroyModal', :class => 'btn btn-danger', 'data-toggle' => 'modal' %>
</div>
<!-- Modal -->
<div id="destroyModal" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Confirm</h3>
  </div>
  <div class="modal-body">
    <p>Are you sure?</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal">Cancel</button>
    <%= link_to raw('<i class="icon-trash icon-white"></i> Destroy'), @app, method: :delete, :class => 'btn btn-danger' %>
  </div>
</div>
<script>
  $(function() {
    $('#destroyModal').modal({
      show: false
    });
  });
</script>

app/views/devices/_form.html.erb
<%= form_for @device, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @device.errors.any? %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h4><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h4>
      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'input-xlarge' %>
    </div>  
  </div>
  <div class="control-group">
    <%= f.label :key, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :key, :class => 'input-xlarge' %>
    </div>  
  </div>
  <div class="form-actions">
    <%= f.button raw('<i class="icon-ok icon-white"></i> Save'), :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<ul class="breadcrumb step-nav">
  <li><%= link_to 'Device List', devices_path %> <span class="divider">/</span>
  <li><%= link_to @device.name, @device %> <span class="divider">/</span>
  <li>Editing
</ul>
<div class="row page-title-container">
  <div class="span6">
    <h2>Editing Device</h2>
  </div>
  <div class="span6">
  </div>
</div>
<%= render 'form' %>

app/views/devices/index.html.erb
<div class="row page-title-container">
  <div class="span6">
    <h2>Device List</h2>
  </div>
  <div class="span6">
    <%= link_to raw('<i class="icon-plus icon-white"></i> New Device'), new_device_path, :class => 'btn btn-success pull-right' %>
  </div>
</div>
<table class="table table-bordered table-striped">
  <tr>
    <th>Name</th>
    <th>Key</th>
  </tr>
<% @devices.each do |device| %>
  <tr>
    <td><%= link_to device.name, device %></td>
    <td><%= device.key %></td>
  </tr>
<% end %>
</table>

app/views/devices/new.html.erb
<ul class="breadcrumb step-nav">
  <li><%= link_to 'Device List', devices_path %> <span class="divider">/</span>
  <li>New
</ul>
<div class="row page-title-container">
  <div class="span6">
    <h2>New Device</h2>
  </div>
  <div class="span6">
  </div>
</div>
<%= render 'form' %>

app/views/devices/show.html.erb
<ul class="breadcrumb step-nav">
  <li><%= link_to 'Device List', devices_path %> <span class="divider">/</span>
  <li><%= @device.name %>
</ul>
<div class="row page-title-container">
  <div class="span6">
    <h2>Device Details</h2>
  </div>
  <div class="span6">
  </div>
</div>
<% if notice.present? %>
<div class="alert alert-info">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <%= notice %>
</div>
<% end %>
<dl class="dl-horizontal detail-container">
  <dt>Name:
  <dd><%= @device.name %>
  <dt>Key:
  <dd><%= @device.key %>
</dl>
<div class="form-actions">
  <%= link_to raw('<i class="icon-edit icon-white"></i> Edit'), edit_device_path(@device), :class => 'btn btn-info' %>
  <%= link_to raw('<i class="icon-trash icon-white"></i> Destroy'), '#destroyModal', :class => 'btn btn-danger', 'data-toggle' => 'modal' %>
</div>
<!-- Modal -->
<div id="destroyModal" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Confirm</h3>
  </div>
  <div class="modal-body">
    <p>Are you sure?</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal">Cancel</button>
    <%= link_to raw('<i class="icon-trash icon-white"></i> Destroy'), @device, method: :delete, :class => 'btn btn-danger' %>
  </div>
</div>
<script>
  $(function() {
    $('#destroyModal').modal({
      show: false
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ranprince</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <div class="row">
    <div class="span3" id="site_title">
      <h1><%= link_to image_tag('logo.png', :alt => 'Ranprince'), root_path %></h1>
    </div>
    <div class="span9 header-nav">
      <ul class="nav nav-pills">
        <li><%= link_to 'Apps', apps_path %>
        <li><%= link_to 'Devices', devices_path %>
      </ul>
    </div>
  </div>
</header>
<div class="row content-container">
  <div class="span12">
    <%= yield %>
  </div>
</div>
<footer>
  <p>Designed and built by <%= link_to 'KICKHOST', 'http://www.kickhost.jp', :target => '_blank' %>.
  <p>Code licensed under <%= link_to 'Apache License v2.0', 'http://www.apache.org/licenses/LICENSE-2.0', :target => '_blank' %>.
</footer>
</body>
</html>

app/views/score_reports/index.html.erb
<ul class="breadcrumb step-nav">
  <li><%= link_to 'Application List', apps_path %> <span class="divider">/</span>
  <li><%= @app.name %> Ranking
</ul>
<div class="row page-title-container">
  <div class="span6">
    <h2><%= @app.name %> Ranking</h2>
  </div>
  <div class="span6">
  </div>
</div>
<div>
  <%= form_for app_ranking_index_path, :remote => true, :method => :get, :html => { :class => 'form-search' } do |f| %>
    <%= hidden_field_tag :time_type, @time_type_name %>
    <div class="navbar navbar-googlenav">
      <div class="navbar-inner">
        <div class="btn-toolbar">
          <div class="btn-group">
            <% TimeType.names.each do |name| %>
            <% class_vlaue = @time_type_name == name ? 'btn active' : 'btn' %>
            <% class_vlaue = 'btn active' if @time_type_name.blank? && name == TimeType::ALL %>
            <%= link_to name, app_ranking_index_path(:device => @device_key, :time_type => name), :class => class_vlaue %>
            <% end %>
          </div>
          <div class="btn-group">
            <%= f.label :device %>
            <%= select_tag :device, options_from_collection_for_select(Device.all, :key, :name, @device_key), :include_blank => true %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<table class="table table-bordered table-striped">
  <tr>
    <th>Rank</th>
    <th>Created at</th>
    <th>
      <%= link_to 'Score', app_ranking_index_path(:order => @order_param, :device => @device_key) %>
      <i class="<%= @order_param == 'desc' ? 'icon-arrow-down' : 'icon-arrow-up' %>"></i>
    </th>
    <th>Device</th>
    <th>Player</th>
  </tr>
  <% @score_reports.each_with_index do |score_report, i| %>
  <tr>
    <td><%= i + 1 %></td>
    <td><%= score_report.created_at %></td>
    <td><%= score_report.score %></td>
    <td><%= score_report.device.name %></td>
    <td><%= score_report.player.name %></td>
  </tr>
  <% end %>
</table>
<script type="text/javascript">
  $(function() {
    $('#device').change(function() { this.form.submit(); });
  });
</script>